### ISSUE TITLE
Demo broken on Node 5.5 & NPM 3.5.3

### ISSUE THREAD

**Issue by mindreframer** [mweststrate/mobservable-reactive2015-demo#1]
fresh git clone from github, npm install && npm start. 

Node was updated yesterday (2016/02/12), so it's currently the most up-to-date version. 

OS: OSX 10.11.1

Something I'm doing wrong? 

```
[HMR] Waiting for update signal from WDS...
index.js:1 Starting mobservable-react-devtools...
warning.js:45 Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `Canvas`.warning @ warning.js:45
invariant.js:46 Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of `Canvas`.
index.js:1 Initialized mobservable-react-devtools.
```

![bug_report_mobservable_error](https://cloud.githubusercontent.com/assets/1232/13026858/87842218-d237-11e5-81e7-b2efe65e65c6.png)
![bug_report_node_version](https://cloud.githubusercontent.com/assets/1232/13026859/8785fbb0-d237-11e5-84e2-57e3dc6e30bd.png)

**Comment by mweststrate** [comment]
Sorry, didn't see your issue earlier, I'll look into it tomorrow!

**Comment by mweststrate** [comment]
Should be fixed now, thanks for reporting! (And apologies for noticing so late, somehow the notifications for this repo were disabled)

**Comment by mindreframer** [comment]
:) great! thx for fixing!
